language: rust
os:
  - linux
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
branches:
  only:
    - dev
    - master
notifications:
  email:
    recipients:
      - ernest@unstable.build
cache: cargo
before_script: 
  - |
    (cargo install rustfmt || true) &&
    export PATH=$HOME/.cargo/bin:$PATH
script:
  - |
    cargo fmt -- --write-mode=diff &&
    cargo build &&
    cargo test
