# rate-limited 1byte echo rpc-perf config
#
# use-case: analyze request/response latency

[general]
threads = 6
connections = 10
duration = 20
windows = 1
protocol = "echo"
tcp-nodelay = false
ipv4 = true
ipv6 = true

[[workload]]
name = "echo"
method = "echo"
rate = 50000

[[workload.parameter]]
style = "static"
size = 1
seed = 0
